### ISSUE TITLE
empty analyses

### ISSUE THREAD

**Issue by carges** [giellalt/lang-mhr#2]
I get an empty analysis after \, see the following example:

```sh
echo "ja \ ja "|hfst-tokenise -cg tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst
"<ja>"
	"ja" ?
: 
"<\\>"
	"\\" N Symbol <W:0.0>
"<>"
	"ʼ" N Symbol <W:0.0>
: 
"<ja>"
	"ja" ?
: 
"<>"
	"ʼ" N Symbol <W:0.0>
:\n
"<>"
	"ʼ" N Symbol <W:0.0>
```

I have the following hfst/hfst-tokenise versions:

```
ls -l /usr/local/bin/hfst-tokenise
lrwxr-xr-x  1 car010  wheel  13 Dec  1 18:55 /usr/local/bin/hfst-tokenise -> hfst-tokenize

hfst-info
No tests selected; printing known data
HFST info version: 0.1
HFST packaging: hfst 3.15.2
HFST version: 3.15.2
HFST long version: 300150002
OpenFst supported
SFST supported
foma supported
Unicode support: ICU
```

**Comment by carges** [comment]
Børre gets the same result as me, and has the following:

❯ dpkg -l|grep hfst
ii  hfst                                          3.15.2+g3754~c78084b3-1~focal1         amd64        Helsinki Finite-State Transducer Technology
ii  libhfst52                                     3.15.2+g3754~c78084b3-1~focal1         amd64        Helsinki Finite-State Transducer Technology Libraries
ii  libhfstospell11:amd64                         0.5.2+g361~884a3441-1~focal1           amd64        HFST spell checker runtime libraries

**Comment by snomos** [comment]
Notice how there are several empty analyses, not only after `\`. It is not related to `\` at all, I would assume. Changed the title of the issue accordingly.

**Comment by flammie** [comment]
I think that the lemma of empty string shows up as apostrophe might help track down the issue. Also: 

```
echo | hfst-lookup src/analyser-gt-desc.hfstol
> 	ʼ+N+Symbol	0,000000
```

The twol has ʼ:0 but no rules to control it, perhaps it is optional soft sign but the symbol string should be exempted from this optionalisation, if it is a soft sign I think `ʼ:0 => :Consonant _ ;` would be a good enough..

**Comment by carges** [comment]
@flammie did you test ```ʼ:0 => :Consonant _ ;``` ?

**Comment by Trondtr** [comment]
Ok, the thing is that the lexicon has entries like 
ылик+N:ы•лʼик N_  "" ;
ясле+N:я•слʼь%{еы%} N_  "(lasten) seimi; (karjan) seimi" 

I must admit I do not know why we have this mark, what follows is either a palatalising vowel (и, я, ...) or a palatal mark (ь). The symbol could also be %^PAL or some symbol never to occur in text. But whether it would help us now I do not know.

**Comment by snomos** [comment]
@rueter may know.

**Comment by rueter** [comment]
When the round peg was shoved into the square hole in the late 1930s,
One 'gressive thing to do was to remove palatal vs non-palatal distinction in the orthography.
The special mark ``` ʼ ``` here is used to indicate that the preceding ```l``` is palatal.
What would you like to use in its place?

**Comment by flammie** [comment]
> The special mark `ʼ` here is used to indicate that the preceding `l` is palatal.
> What would you like to use in its place?

Unicode apostrophe is a good palatalisation marker, but we need twol rules to make sure it doesn't get deleted when it is analysed as its own token symbol, i.e. analysing empty string should not get apostrophe as a reading. Having empty string analysed as something breaks a lot of tokenisations and stuff.

**Comment by flammie** [comment]
`make check` fails with adjectives but I think it is unrelated? @rueter can you check ’ still works?

**Comment by Trondtr** [comment]
The error is in the makefile. It expects +A, but we have changed the analysis:
```
кугу
кугу	кугу+A+Attr	0,000000
кугу	кугу+Ex/A+Der/MWN+N+Attr	0,000000
кугу	кугу+Ex/A+Der/MWN+N+Sg+Nom	0,000000
кугу	кугу+N+Attr	0,000000
кугу	кугу+N+Sg+Nom	0,000000
```
I change the expected tag to +A+Attr. The errors go down from 10500 to 25, a clear step forward.

**Comment by rueter** [comment]
> echo | hfst-lookup src/analyser-gt-desc.hfstol

Locally, I have checked this the following languages: mhr, myv, kpv, koi, mdf, vro, apu,

Only kpv seems to have a problem at present with NULL:NULL+N

```
LM8-400-11:lang-kpv rueter$ echo | hfst-lookup src/analyser-gt-desc.hfstol
> 	+N+Sg+Nom	0.000000

```
