### ISSUE TITLE
The hfst mhr analyzer pushes unrecognized tokens off the margin instead of tagging them ‹?›

### ISSUE THREAD

**Issue by rueter** [giellalt/lang-mhr#5]
The analyzers:
```
echo 'car Авиафар Почешыже Галилей, Иудей, Иерусалим, Идумей гыч, ' | hfst-tokenise -g $GIELLA_HOME/lang-mhr/tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst
```
And 
```
echo 'car Авиафар Почешыже Галилей, Иудей, Иерусалим, Идумей гыч, ' | hfst-tokenise -S -g --giella-cg -W $GIELLA_HOME/lang-mhr/tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst| l
```
both treat three unrecognized tokens ```car```, ```Авиафар``` and ```Идумей``` in a non-acceptable manner:
Instead of tagging them with a ‹?› question mark, the analyzer pushes them off the left margin.
<img width="586" alt="Screenshot 2023-01-11 at 14 20 10" src="https://user-images.githubusercontent.com/14276164/211825206-bc28bb73-0e4e-40c4-9771-dadd3265e3a5.png">

**Comment by unhammer** [comment]
As if they were non-alphabetic characters. This kind of thing is only supposed to happen with stuff that shouldn't get an analysis, e.g. whitespace. I'll take a look at the pmscript.

(btw `hfst-tokenise -S -g --giella-cg -W`  is equivalent to simply `hfst-tokenise -S -g`)

**Comment by unhammer** [comment]
@rueter Does it work after https://github.com/giellalt/lang-mhr/commit/8e894a1ed4fb5bd6c13e746508c6867fabaf42ba ?

**Comment by rueter** [comment]
Yes, @unhammer it now seems to work as expected. :-)
